
/* Generated by res2swc.xml from res folder */
package com.resource
{
	import flash.display.BitmapData;
	import flash.display.Bitmap;
	import flash.media.Sound;
	import flash.utils.ByteArray;
	import flash.text.Font;
public class Resource
{
    /* Images */
    [Embed(source='/Users/pingnak/work/AIRvsCocos/AIR/res/Smiley.png')]
    public static const cls_Smiley_png : Class;
    public static const Smiley_png : BitmapData = (new cls_Smiley_png()).bitmapData;

    /* Sounds */

    /* Fonts (make sure font file name matches the internal font name) */

    /* SWF files (not for iOS) */

    /* Generic ByteArray data */

}
}
